version: "3.7"

services:
  socailbookDb:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "1100:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

networks:
  socailbook_net:
    external:
      name: socailbook_net
