version: "3.7"

services:
  mongodb:
    image: mongo:latest
    container_name: socialbook_mongodb
    restart: always
    ports:
      - 27017:27017
    networks:
      - socailbook_net
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
networks:
  socailbook_net:
    external:
      name: socailbook_net
